name: Cleanup Workflow

on:
  schedule:
    - cron: '0 12 * * *' # 每天正午12点（UTC）自动运行
  workflow_dispatch:      # 支持手动触发

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Install GitHub CLI
        run: sudo apt-get install gh jq -y

      - name: Delete old workflow runs
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh auth login --with-token < <(echo "$GH_TOKEN")
          for WF_ID in $(gh api repos/${{ github.repository }}/actions/workflows | jq -r '.workflows[].id'); do
            RUN_IDS=$(gh api repos/${{ github.repository }}/actions/workflows/$WF_ID/runs?per_page=100 | jq -r '.workflow_runs | sort_by(.created_at) | reverse | .[5:] | .[].id')
            for ID in $RUN_IDS; do
              gh api --method DELETE repos/${{ github.repository }}/actions/runs/$ID
              echo "Deleted run $ID of workflow $WF_ID"
            done
          done
