name: Sync _worker.js From BPB-Worker-Panel

on:
  schedule:
    - cron: '0 * * * *' # 每小时运行一次
  workflow_dispatch:

jobs:
  sync-worker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout your repo
      uses: actions/checkout@v4

    - name: Get latest release info from BPB-Worker-Panel
      id: get_release
      run: |
        api_url="https://api.github.com/repos/bia-pain-bache/BPB-Worker-Panel/releases/latest"
        release_info=$(curl -s $api_url)
        tag_name=$(echo "$release_info" | jq -r .tag_name)
        zip_url=$(echo "$release_info" | jq -r '.assets[] | select(.name=="worker.zip") | .browser_download_url')
        echo "tag_name=$tag_name" >> $GITHUB_OUTPUT
        echo "zip_url=$zip_url" >> $GITHUB_OUTPUT

    - name: Download worker.zip
      run: |
        curl -L "${{ steps.get_release.outputs.zip_url }}" -o worker.zip

    - name: Unzip _worker.js (overwrite in repo root)
      run: |
        unzip -o worker.zip _worker.js

    - name: Update README.md version
      run: |
        tag="${{ steps.get_release.outputs.tag_name }}"
        sed -i "s/V 1\..*/V 1.${tag}/g" README.md

    - name: Commit & Push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add _worker.js README.md
        git commit -m "Sync _worker.js & README.md version to ${{ steps.get_release.outputs.tag_name }}" || echo "Nothing to commit"
        git push origin main
