name: Sync & Delete

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  sync-worker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout your repo with PAT
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.MY_BLOG_PAT }}

    - name: Get latest release info from BPB-Worker-Panel
      id: get_release
      run: |
        api_url="https://api.github.com/repos/bia-pain-bache/BPB-Worker-Panel/releases/latest"
        release_info=$(curl -s $api_url)
        tag_name=$(echo "$release_info" | jq -r .tag_name)
        zip_url=$(echo "$release_info" | jq -r '.assets[] | select(.name=="worker.zip") | .browser_download_url')
        echo "tag_name=$tag_name" >> $GITHUB_OUTPUT
        echo "zip_url=$zip_url" >> $GITHUB_OUTPUT

    - name: Download worker.zip
      run: |
        curl -L "${{ steps.get_release.outputs.zip_url }}" -o worker.zip

    - name: Unzip _worker.js (overwrite in repo root)
      run: |
        unzip -o worker.zip _worker.js

    - name: Update README.md version
      run: |
        random_version=$(date +%s%N | cut -b10-19)
        sed -i "s/This is a testing blog program.*/This is a testing blog program:${random_version}/g" README.md

    - name: Commit & Push changes
      run: |
        git config user.name "vampireisoves"
        git config user.email "893751627@qq.com"
        git add _worker.js README.md
        git commit -m "Sync _worker.js & README.md version to ${{ steps.get_release.outputs.tag_name }}" || echo "Nothing to commit"
        git push origin main
  del_runs:
    needs: sync-worker
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - name: Delete workflow runs for remote repo
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: 'vampireisoves/mytestblog'
          retain_days: 0
          keep_minimum_runs: 5
