name: Sync _worker.js and Release Version from Upstream

on:
  schedule:
    - cron: '0 * * * *' # 每小时自动触发
  workflow_dispatch: # 可手动触发

jobs:
  sync-upstream:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout self
        uses: actions/checkout@v4

      - name: Get latest release info
        id: get_release
        run: |
          upstream_repo="bia-pain-bache/BPB-Worker-Panel"
          latest_tag=$(gh release list --repo $upstream_repo --limit 1 --json tagName | jq -r '.[0].tagName')
          echo "latest_tag=$latest_tag" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download worker.zip from latest release
        run: |
          upstream_repo="bia-pain-bache/BPB-Worker-Panel"
          asset_url=$(gh release view $latest_tag --repo $upstream_repo --json assets | jq -r '.assets[] | select(.name=="worker.zip") | .url')
          echo "Asset url: $asset_url"
          if [ -z "$asset_url" ]; then
            echo "worker.zip asset not found in latest release $latest_tag"
            exit 1
          fi
          curl -L -o worker.zip -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" $asset_url
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract _worker.js (overwrites repo file)
        run: |
          unzip -o worker.zip _worker.js
          if [ ! -f _worker.js ]; then
            echo "_worker.js not found after unzip"
            exit 1
          fi

      - name: Update README.md version
        run: |
          sed -i "s/V 1\.[0-9A-Za-z\.\-\_]*/V 1.${{ env.latest_tag }}/g" README.md

      - name: Create and push branch
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          branch="sync-workerjs-${{ env.latest_tag }}"
          git checkout -b "$branch"
          git add _worker.js README.md
          git commit -m "Sync _worker.js and update version to ${{ env.latest_tag }} from upstream release"
          git push origin "$branch"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: sync-workerjs-${{ env.latest_tag }}
          title: "Sync _worker.js and update version to ${{ env.latest_tag }} from upstream release"
          body: "This PR automatically syncs _worker.js and updates README.md version."
